#!/bin/bash

# Adapted from code by Sinhdre Sorus - sindresorhus.com

set -e

changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

check_run() {
  echo "$changed_files" | egrep --quiet "$1" && eval "$2"
}

# Handle pnpm install when any pnpm-lock.yaml is modified
check_run 'pnpm-lock.yaml' "pnpm install"

# Handle npm, yarn, and bundle installs if those lock files are present (in case non-pnpm is used for some parts of the repo)
check_run 'package-lock.json' "npm install"
check_run 'yarn.lock' "yarn install"
check_run 'Gemfile.lock' "bundle install"
